.PHONY: version

version:
	echo "$(MAKE_VERSION)"

# 2.1 Was würde passieren, wenn ein File mit dem Namen version erstellt würde?
# Dann würde im Terminal nicht mehr die Make-Version ausgegeben werden, sondern folgenden Meldung: make: 'version' is up to date.

# 2.2 Wie kann sichergestellt werden, dass der Vorgang version zuverlässig ausgeführt wird?
# Mit .PHONY: version kann sichergestellt werden, dass der Vorgang version zuverlässig ausgeführt wird,
# auch wenn eine Datei mit dem Namen version existiert.