services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    hostname: gitlab.local
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost:8088'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
        gitlab_rails['initial_root_password'] = 'iw6+ASoyDDgWJOKxdK9MmtWE8EX4SnoIbDxU4TP0DtE='
        letsencrypt['enable'] = false
        puma['worker_processes'] = 2
        sidekiq['max_concurrency'] = 10
    ports:
      - '8088:8088'
      - '2222:22'
    volumes:
      - './gitlab/config:/etc/gitlab'
      - './gitlab/logs:/var/log/gitlab'
      - './gitlab/data:/var/opt/gitlab'
    networks:
      - gitlab-network
    shm_size: '256m'

  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    restart: always
    volumes:
      - './gitlab-runner/config:/etc/gitlab-runner'
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - gitlab-network
    depends_on:
      - gitlab

networks:
  gitlab-network:
    driver: bridge

# Command um eine runner zu registrieren
# Command um einen runner zu registrieren: docker network ls
# docker run --rm -it -v ./gitlab-runner/config:/etc/gitlab-runner --network 5_gitlab_gitlab-network gitlab/gitlab-runner:latest register --non-interactive --url "http://gitlab:8088" --registration-token "glrt-c33ZMZ4uZcwGct-iBjD-dW86MQp0OjEKdToxCw.01.1213pc572" --executor "docker" --docker-image "alpine:latest" --description "docker-runner" --docker-network-mode "5_gitlab_gitlab-network" --docker-volumes "/var/run/docker.sock:/var/run/docker.sock"